---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  CloudFormation template to create an S3 bucket with a bucket policy for access
  control.

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "my-example-bucket-name"
      VersioningConfiguration:
        Status: "Enabled"
      Tags:
        - Key: "Environment"
          Value: "Production"

  MyS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "${MyS3Bucket.Arn}"
              - !Sub "${MyS3Bucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false" # Enforce HTTPS access only

Outputs:
  BucketName:
    Description: "The name of the created S3 bucket"
    Value: !Ref MyS3Bucket

  BucketArn:
    Description: "The ARN of the created S3 bucket"
    Value: !GetAtt MyS3Bucket.Arn
